title: Workshop on the Norwegian Web Archive
description: Documentation with how-to guide and explanation of tools and services
theme: just-the-docs

url: https://joncto.github.io/research-services/

logo: "/assets/images/just-the-docs.png"
favicon_ico: "/assets/images/favicon.ico"
search_enabled: true


aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
